# Generated by Django 4.0.3 on 2022-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_remove_user_is_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id_epreuve', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_fichier_epreuve', models.FileField(upload_to='bepreuve/files/epreuve/')),
                ('nom_fichier_correction', models.FileField(upload_to='bepreuve/files/epreuve/')),
                ('nom_epreuve', models.CharField(max_length=50)),
                ('niveau_epreuve', models.CharField(max_length=50)),
                ('annee_epreuve', models.IntegerField()),
                ('matiere_epreuve', models.CharField(max_length=50)),
                ('nom_prof', models.CharField(max_length=50)),
                ('nom_filliere', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filliere',
            fields=[
                ('id_filliere', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_filliere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_prof', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=50)),
            ],
        ),
    ]
