# Generated by Django 4.0.3 on 2022-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_epreuve_filliere_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
