# Generated by Django 4.0.3 on 2022-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_user_adresse_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='nom_fichier_correction',
            field=models.FileField(upload_to='files/epreuve/'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='nom_fichier_epreuve',
            field=models.FileField(upload_to='files/epreuve/'),
        ),
    ]
